package co.simplon.puzzles;

import java.util.Scanner;

/*
 * Implement a guess-my-random-number puzzle.
 *
 * Given a random number generated by the program, give a limited number of attempts (4) to the user to guess that number.
 *
 * Help: ThreadLocalRandom class.
 *
 * To test the guess you can set temporarily a hard-coded value instead of a random one.
 *
 * We consider that user input is always a string representing a number, convert it without handling eventual parsing error.
 *
 * If the input is the right number, sys out "Good guess!" and program ends.
 *
 * If the input is not the right number but the user have at least one more attempt, sys err "No! Try again (attempts/4)..." where "attempts" is the number of used attempts.
 *
 * If the input is not the right number and the user do not have any remaining attempt, sys err "No! Sorry you have reached the maximum attempts (4/4)...".
 *
 * Examples (console output):
 * Welcome to GuessMyNumber puzzle.
 * Try to guess my number (between 1 and 20 inclusives), you have 4 attempts...
 * 1
 * No! Try again (1/4)...
 * 5
 * No! Try again (2/4)...
 * 10
 * No! Try again (3/4)...
 * 5
 * No! Sorry you have reached the maximum attempts (4/4) :P
 * Thank you, hope it was fun.
 */
public class GuessMyNumber {

    public static void main(String[] args) {
	System.out.println("Welcome to GuessMyNumber puzzle.");
	System.out.println("Try to guess my number (between 1 and 20 inclusives), you have max 4 attempts...");
	// You may initialize some variables before the loop...
	try (Scanner in = new Scanner(System.in)) {
	    program: while (true) {
		String input = in.nextLine();
		if (input.equals("exit")) {
		    break program;
		}
		// Puzzle code here after:

		// End of puzzle code
	    }
	}
	System.out.println("Thank you, hope it was fun.");
    }
}
